# Workflow의 이름
name: Github Actions 실행해보기

# Event: 실행되는 시점을 설정
# main이라는 브랜치에 push가 발생하면 아래의 jobs을 실행
on:
    push:
        branches:
            - main

# 하나의 Workflow에는 여러개의 Job을 설정할 수 있음
# Job은 병렬로 실행됨
jobs:
  # Job을 식별하기 위한 id
  My-Deploy-Job:
    # Job을 실행하는 환경
    # ubuntu-latest는 Github Actions에서 제공하는 최신 Ubuntu 환경임
    runs-on: ubuntu-latest

    # Step: 특정 작업을 수행하는 가장 작은 단위
    # Job은 여러개의 Step으로 구성됨
    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "첫 번째 줄"
          echo "두 번째 줄"
          echo "세 번째 줄"
      - name: Github Actions 자체에 저장되어있는 변수 사용하기
      # Github Actions에는 여러가지 변수들이 미리 정의되어 있음
      # 이 변수들은 $로 시작함
      # GITHUB_SHA: 현재 Commit의 SHA 값
      # GITHUB_REPOSITORY: 현재 Repository의 이름
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
      - name: Github Actions에 저장되어있는 환경 변수 사용하기
        run: |
          echo ${{ secrets.MY_HOBBY }}
          echo ${{ secrets.MY_NAME }}
      